name: pomotimer
description: Pomodoro Timer. Demostration of Local Notification.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.1+1
  google_fonts: ^2.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - restend.mp3
    - workend.mp3

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Light.ttf
          weight: 200
    - family: SquadaOne
      fonts:
        - asset: assets/SquadaOne-Regular.ttf
